<!--Partial Footer-->
<?php
echo
'<div class="row">
                <div class="footer-col">
                    <h4>Overview</h4>
                    <ul>
                        <li><a href="index.php">Home</a></li>
                        <li><a href="products.php">Products</a></li>
                        <li><a href="Activities.php">Activities</a></li>
                        <li><a href="joinus.php">Work for us</a></li>
                        <li><a href="locations.php">Visit Us</a></li>
                        <li><a href="enquiry.php">FAQ</a></li>
                        <li><a href="registration.php">Register</a></li>
                        <li><a href="login.php">Login</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4><a href="about.php">The Team</a></h4>
                    <ul>
                        <li><a href="aboutme1.php">Kelvin</a></li>
                        <li><a href="aboutme2.php">Patrick</a></li>
                        <li><a href="aboutme3.php">Ricardo</a></li>
                        <li><a href="aboutme4.php">Wei Bao</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>Extra</h4>
                    <ul>
                        <li><a href="acknowledgement.php">Acknowledgements</a></li>
                        <li><a href="enhancements.php">Enhancements</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>Follow Us</h4>
                    <div class="social-links">
                        <a class="responsive-hover-img" href="https://www.instagram.com/p/DGdDmXOPD-J/">
                            <img class="responsive-hover" src="images/Icons/bxl-instagram.svg" alt="Instagram">
                        </a>
                        <a class="responsive-hover-img" href="https://www.facebook.com/profile.php?id=61554234958482">
                            <img class="responsive-hover" src="images/Icons/bxl-facebook-circle.svg" alt="Facebook">
                        </a>
                    </div>
                    <h4>Contact Us</h4>
                    <p>Phone: +60 11-1653 1886</p>
                    <p>Email: <a href="mailto:brewngo.coffee@gmail.com">brewngo.coffee@gmail.com</a></p>
                </div>
                <div class="footer-col">
                    <h4>Latest from us</h4>
                    <iframe class="responsive-hover-img no-scroll"
                        src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Fpermalink.php%3Fstory_fbid%3Dpfbid0Ro5XUkWsugqwP6cFKBsd7MWcqumoxyF4wDd8xdPcGCLZK7udVGAtrpvjBrnVUgJSl%26id%3D61554234958482&show_text=true&width=500"
                        allowfullscreen
                        allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"></iframe>
                </div>
                <div class="footer-col">
                    <small>&copy; 2025 Brew & Go Coffee</small>
                </div>
            </div>'
?>