<?php
echo
'<nav>
        <div class="nav-selector">
            <a href="index.html"><img src="images/Brew&Go_logo.png" alt="Brew & Go logo"></a>
            <a href="index.html">Brew & Go. Coffee</a>
        </div>
        <ul>
            <li>
                <div class="Dropdown_Start"><a href="products.html">Products</a>
                    <div class="Dropdown_Content">
                        <ul>
                            <li><a href="product1.html">Basic Brew</a></li>
                            <li><a href="product2.html">Artisan Brew</a></li>
                            <li><a href="product3.html">Non-Coffee</a></li>
                            <li><a href="product4.html">Hot Beverages</a></li>
                        </ul>
                    </div>
                </div>
            </li>
            <li>
                <div class="Dropdown_Start"> <a href="activities.html">Activities</a>
                    <div class="Dropdown_Content">
                        <ul>
                            <li><a href="Current.html">Current</a></li>
                            <li><a href="Coming_Soon.html">Coming Soon</a></li>
                            <li><a href="Past.html">Past</a></li>
                        </ul>
                    </div>
                </div>
            </li>
            <li><a href="joinus.html">Join Us</a></li>
            <li><a href="enquiry.html">Enquiry</a></li>
            <li><a href="registration.html">Membership</a></li>
            <li id="nav-login" class="nav-selector">
                <a href="login.html">Login</a>
                <a class="center" href="login.html"><img alt="Login icon" src="images/Icons/user-circle-svgrepo-com(black).svg"></a>
            </li>
        </ul>
    </nav>'
?>